-keep class net.crinoidea.liberty.admin.LibertyAdminReceiver { *; }
-keep class net.crinoidea.liberty.ui.PolicyComplianceActivity { *; }
-keepattributes RuntimeVisibleAnnotations,AnnotationDefault
-allowaccessmodification
